apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector-metrics
  namespace: fraud-detection
spec:
  selector:
    app: anomaly-detector
  ports:
  - name: metrics
    port: 8001
    targetPort: 8001
