apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector-service
  namespace: fraud-detection
spec:
  selector:
    app: anomaly-detector
  ports:
  - name: api
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 8001
    targetPort: 8001
  type: LoadBalancer