apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fraud-detection
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'anomaly-detector'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - fraud-detection
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: anomaly-detector-service
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: metrics
        - target_label: __address__
          replacement: anomaly-detector-service:8001
        - targets: ['anomaly-detector-metrics.fraud-detection.svc.cluster.local:8001']