apiVersion: v2
name: fraud-detection
description: A Helm chart for fraud detection service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.5.8"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.11.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "22.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled